#! /bin/sh
set -o nounset -o xtrace

destdir=/tmp/rpmize
spec=${destdir}.spec
rm --force ${spec}
boundary=$'\n__RPMIZE__\n'

function rpmquery
{
  local rpm=$1 format=${2:-''} result
  test -f "${rpm}" && rpm="--package ${rpm}"
  result=$(LANG=C rpm --query --queryformat=${format} ${rpm})
  (($?)) && return 1
  echo "${result}"
  return 0
}

#----------------------------------------------------------------------
# estimate default values
#----------------------------------------------------------------------
dirname=${PWD##*/}
package=$(echo ${dirname} | sed --expression='s/[0-9.-]*$//')
version=${dirname#${package}}
version=${version#-}

name=rpmized-${package}
if $(rpmquery ${name})
then
  # There is rpmized package installed.
  rpm=${name}
elif $(rpmquery ${package})
then
  # There is none-rpmized package installed.
  rpm=${package}
  release=0
else
  # default values
  version=${version:-1.0}
  release=0
  summary="Package ${name} created with rpmize"
  license=MIT
  description="Package ${name} created with rpmize"
fi

# Extract variables from the rpm package for each unset variable.
version=${version:-$(rpmquery ${rpm} '%{VERSION}')} # TODO: バージョンが異なっていたらrelease=0
release=${release:-$(rpmquery ${rpm} '%{RELEASE}')} ; release=${release//[^0-9]/} ; release=$((${release:-0} + 1))
summary=${summary:-$(rpmquery ${rpm} '%{SUMMARY}')}
license=${license:-$(rpmquery ${rpm} '%{LICENSE}')}
description=${description:-$(rpmquery ${rpm} '%{DESCRIPTION}')}

#----------------------------------------------------------------------
# edit sections
#----------------------------------------------------------------------
# using `%#' for escape rpm macro because `#%%' is usually used.
sections=${description#*${boundary}}
if test "$sections" = "$description"
then
  sections="%#install
%#{configure}
%#{makeinstall}"
else
  description=${description%%${boundary}${sections}}
fi
sections=${sections//%#/%}
echo "${sections}" 1>${spec}
${EDITOR} ${spec}
sections=$(cat ${spec})
description=${description}${boundary}${sections//%/%#}

#----------------------------------------------------------------------
# create spec file
#----------------------------------------------------------------------
cat - <<EOF | tee ${spec}
%define _prefix /usr/local
%define _builddir ${PWD}
%define __perl_provides %{nil}
%define __perl_requires %{nil}

Name: ${name}
Version: ${version}
Release: ${release}
Summary: ${summary}
License: ${license}
%description
${description}
${sections}
%files
%defattr(-,root,root,-)
EOF
# You can modify the spec if you want.
${EDITOR} ${spec}

#----------------------------------------------------------------------
# do install
#----------------------------------------------------------------------
if test -d "${destdir}"
then
  echo -n "May I use ${destdir}?[y/N]"
  read
  if ! [[ "${REPLY}" =~ ^([Yy]([Ee][Ss])?)$ ]]
  then
    rm --force --recursive ${destdir}
  fi
fi
if test ! -d "${destdir}"
then
  sed --expression='1s/^/%define __check_files %{nil}\n/' --in-place ${spec}
  rpmbuild --buildroot=${destdir} -bi ${spec} || exit
  grep --invert-match --fixed-string '%define __check_files %{nil}' ${spec} | tee ${spec} 1>/dev/null
fi

#----------------------------------------------------------------------
# extract %files section automatically
#----------------------------------------------------------------------
info=''
for entry in $(find ${destdir}/)
do
  entry=${entry#${destdir}}

  if test -d "${destdir}${entry}"
  then # entry is directory
    if test -d "${entry}"
    then # entry already exists on the system
      owning=$(rpm --query --file ${entry})
      if test "${owning##${name}}" = "${owning}"
      then # do nothing if it is not mine
        echo "#%dir ${entry}"
        continue
      fi
    fi
    echo "%dir ${entry}"
  else # entry is file
    case "${entry}" in
      # TODO: */man[0-9]/*) entry=${entry%%.gz} ; echo "${entry}" ;;
      # TODO: %config
      INSTALL|NEWS|README|AUTHORS|ChangeLog|COPYING.LIB|COPYING.LESSER|COPYING)
        echo "%doc ${entry}"
        ;;
      */share/info/dir)
        echo "%exclude ${entry}"
        ;;
      */share/info/*.info*)
        entry=${entry%.gz}
        entry=${entry%.bz2}
        info+=$'\n'"  /sbin/install-info@OPTION@ ${entry} %{_infodir}/dir"
        echo "${entry}"
        ;;
      *)
        echo "${entry}"
        ;;
    esac
  fi
done 1>>${spec}

if test "${info}" != ''
then
  # TODO: Prereq: install-info
  cat - <<EOF 1>>${spec}
%post
if test "\$1" = "1"
then${info//@OPTION@/}
fi
%preun
if test "\$1" = "0"
then${info//@OPTION@/ --delete}
fi
EOF
fi

chmod -w ${spec}
${EDITOR} ${spec}

#----------------------------------------------------------------------
# build rpm
#----------------------------------------------------------------------
# Skip with hacks because it is already installed into DESTDIR.
sed --expression='s/^%\(prep\|build\|install\)/%\1\nexit/g' --in-place ${spec}
rpmbuild --buildroot=${destdir} --rmspec -bb ${spec} && rm --force --recursive ${destdir}
