#! /bin/sh
set -o nounset -o xtrace
VERSION=1.7.0

destdir=/tmp/rpmize
spec=${destdir}.spec
rm --force ${spec}
boundary=$'\n__RPMIZE__\n'

function rpmquery
{
  local rpm=$1 format=${2:-''} result
  test -f "${rpm}" && rpm="--package ${rpm}"
  result=$(LANG=C rpm --query --queryformat=${format} ${rpm})
  (($?)) && return 1
  echo "${result}"
  return 0
}

#----------------------------------------------------------------------
# estimate default values
#----------------------------------------------------------------------
dirname=${PWD##*/}
package=$(echo ${dirname} | sed --expression='s/-v\?[0-9.]*$//')
version=${dirname#${package}}
version=${version#-}
version=${version#v}

name=rpmized-${package}
rpm=''
if $(rpmquery ${name})
then
  # There is rpmized package installed.
  rpm=${name}
elif $(rpmquery ${package})
then
  # There is none-rpmized package installed.
  rpm=${package}
  release=0
fi

if test -n "${rpm}"
then
  # Extract variables from the rpm package for each unset variable.
  if test "${version}" != "$(rpmquery ${rpm} '%{VERSION}')"
  then
    release=0
  fi
  version="${version:-$(rpmquery ${rpm} '%{VERSION}')}"
  release="${release:-$(rpmquery ${rpm} '%{RELEASE}')}" ; release=${release//[^0-9]/} ; release=$((${release:-0} + 1))
  summary="${summary:-$(rpmquery ${rpm} '%{SUMMARY}')}"
  license="${license:-$(rpmquery ${rpm} '%{LICENSE}')}"
  description="${description:-$(rpmquery ${rpm} '%{DESCRIPTION}')}"
else
  # default values
  version=${version:-0.0.0}
  release=1
  summary="Package ${name} created with rpmize"
  license=MIT
  description="Package ${name} created with rpmize"
fi

#----------------------------------------------------------------------
# edit sections
#----------------------------------------------------------------------
# using `%#' for escape rpm macro because `#%%' is usually used.
sections=${description#*${boundary}}
if test "$sections" = "$description"
then
  sections="%#install
%#{configure}
%#{makeinstall}"
else
  description=${description%%${boundary}${sections}}
fi
sections=${sections//%#/%}
echo "${sections}" 1>${spec}
${EDITOR} ${spec}
sections=$(cat ${spec})
description=${description}${boundary}${sections//%/%#}

#----------------------------------------------------------------------
# create spec file
#----------------------------------------------------------------------
cat - <<EOF | tee ${spec}
%define _prefix /usr/local
%define _builddir ${PWD}
%define __perl_provides %{nil}
%define __perl_requires %{nil}

Name: ${name}
Version: ${version}
Release: ${release}
Summary: ${summary}
License: ${license}
%description
${description}
${sections}
%files
%defattr(-,root,root,-)
EOF
# You can modify the spec if you want.
${EDITOR} ${spec}

#----------------------------------------------------------------------
# do install
#----------------------------------------------------------------------
if test -d "${destdir}"
then
  echo -n "May I use ${destdir}?[y/N]"
  read
  if ! [[ "${REPLY}" =~ ^([Yy]([Ee][Ss])?)$ ]]
  then
    rm --force --recursive ${destdir}
  fi
fi
if test ! -d "${destdir}"
then
  sed --expression='1s/^/%define __check_files %{nil}\n/' --in-place ${spec}
  rpmbuild --buildroot=${destdir} -bi ${spec} || exit
  grep --invert-match --fixed-string '%define __check_files %{nil}' ${spec} | tee ${spec} 1>/dev/null
fi

#----------------------------------------------------------------------
# extract %files section automatically
#----------------------------------------------------------------------
info=''
function put_entry()
{
  command=''
  if ((1 < $#))
  then
    command="$1 "
    shift
  fi
  echo "${command}${1//[^0-9a-zA-Z.\/:_-]/?}"
}
IFS=$'\n'
for entry in $(find ${destdir}/)
do
  entry="${entry#${destdir}}"

  if test -d "${destdir}${entry}"
  then # entry is directory
    if test -d "${entry}"
    then # entry already exists on the system
      owning=$(rpm --query --file "${entry}")
      if test "${owning##${name}}" = "${owning}"
      then # do nothing if it is not mine
        put_entry '#%dir' "${entry}"
        continue
      fi
    fi
    put_entry '%dir' "${entry}"
  else # entry is file
    case "${entry}" in
      # TODO: */man[0-9]/*) entry="${entry%%.gz}" ; put_entry "${entry}" ;;
      # TODO: %config
      INSTALL|NEWS|README|AUTHORS|ChangeLog|COPYING.LIB|COPYING.LESSER|COPYING)
        put_entry '%doc' "${entry}"
        ;;
      */share/info/dir)
        put_entry '%exclude' "${entry}"
        ;;
      */share/info/*.info*)
        entry="${entry%.gz}"
        entry="${entry%.bz2}"
        info+=$'\n'"  /sbin/install-info@OPTION@ "'"'"${entry}"'"'" %{_infodir}/dir"
        put_entry "${entry}"
        ;;
      *)
        put_entry "${entry}"
        ;;
    esac
  fi
done 1>>${spec}

if test "${info}" != ''
then
  # TODO: Prereq: install-info
  cat - <<EOF 1>>${spec}
%post
if test "\$1" = "1"
then${info//@OPTION@/}
fi
%preun
if test "\$1" = "0"
then${info//@OPTION@/ --delete}
fi
EOF
fi

chmod -w ${spec}
${EDITOR} ${spec}

#----------------------------------------------------------------------
# build rpm
#----------------------------------------------------------------------
# Skip with hacks because it is already installed into DESTDIR.
sed --expression='s/^%\(prep\|build\|install\)/%\1\nexit/g' --in-place ${spec}
rpmbuild --buildroot=${destdir} --rmspec -bb ${spec} && rm --force --recursive ${destdir}
